name: ml-heroku-fastapi
channels:
  - conda-forge
dependencies:
  - python=3.8
  - mamba
  - scikit-learn
  - dvc
  - dvc-s3
  - pandas
  - numpy
  - pytest
  - jupyterlab
  - fastapi
  - uvicorn
  - autopep8
  - flake8